fix IOOS ngdac links
ioos/ioos.github.io pull request #8
Opened 2023-08-23 14:28 UTC by ocefpaf

@kbailey-noaa this should fix all the references to ioosngdac in this page.

2023-08-23 14:47 UTC, kbailey-noaa commented on _docs/index.md
>  The IOOS National Glider DAC is the official Data Assembly Center (DAC) for all IOOS underwater glider activities.  The Wiki provides glider operators and IOOS data providers technical details on the
Can you also please update this paragraph to:
The IOOS National Glider DAC is the official Data Assembly Center (DAC) for all IOOS underwater glider activities. The Glider DAC documentation provides glider operators and data providers technical details on netCDF data format specifications, information on data provider registration and data set submission processes for contributing real-time and delayed-mode glider data sets to the DAC. The Glider DAC GitHub is the main repository for glider DAC code and tools, and can be used to submit issues or request enhancements to the Glider DAC. The Glider DAC website includes map-based visualizations, data access links, and information about the Underwater Glider User Group (UG2).

2023-08-23 14:48 UTC, kbailey-noaa requested changes
Changes requested for row 28

2023-08-23 14:54 UTC, ocefpaf commented on _docs/index.md
>  The IOOS National Glider DAC is the official Data Assembly Center (DAC) for all IOOS underwater glider activities.  The Wiki provides glider operators and IOOS data providers technical details on the
Done!

2023-09-13 15:34 UTC, ocefpaf commented
> Changes requested for row 28

Should be OK now.

Sorry I forgot to comment here, the change was implemented a while back.

2023-09-14 17:12 UTC, kbailey-noaa approved these changes

2023-09-14 17:12 UTC, merged